// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 Jnana Project

// Live one-way Markdown mirror. SQLite stays the source of truth; every save
// rewrites that note's .md in a folder the user picked, so notes stay readable,
// greppable and git-able without Jnana. The folder is never read back: edits
// made there are overwritten on the next save.

import { invoke } from '@tauri-apps/api/core'
import { open } from '@tauri-apps/plugin-dialog'
import type { Note } from '../types'
import { getNoteType } from '../lib/noteTypes'
import { toast } from '../lib/toast'
import { log } from '../lib/logger'
import { exportNoteContent, safeName } from './export'

/** note id → file name written for it in the mirror folder. */
export type MirrorIndex = Record<string, string>

export interface MirrorPlan {
  index: MirrorIndex
  /** File to (re)write for this note, or null. */
  write: string | null
  /** File of this note to delete (its previous name), or null. */
  remove: string | null
}

const INDEX_KEY = 'jnana.mirror.index.v1'

/** Plain notes, and typed notes whose type projects to markdown. A canvas's raw JSON isn't a readable .md. */
export function isMirrorable(note: Note): boolean {
  if (!note.kind) return true
  return !!getNoteType(note)?.toExportMarkdown
}

export function planDelete(index: MirrorIndex, id: string): MirrorPlan {
  const current = index[id]
  if (!current) return { index, write: null, remove: null }
  const next = { ...index }
  delete next[id]
  return { index: next, write: null, remove: current }
}

export function planSave(index: MirrorIndex, note: Note): MirrorPlan {
  if (!isMirrorable(note)) return planDelete(index, note.id)
  const base = safeName(note.title)
  // Case-insensitive: Windows and macOS file systems treat "Same.md" and "same.md" as one file.
  const plain = `${base}.md`.toLowerCase()
  const taken = Object.entries(index).some(([id, name]) => id !== note.id && name.toLowerCase() === plain)
  const name = taken ? `${base} (${note.id.slice(0, 8)}).md` : `${base}.md`
  const current = index[note.id]
  return {
    index: { ...index, [note.id]: name },
    write: name,
    // A case-only rename writes over the same file on disk; removing the "old" name would delete it.
    remove: current && current.toLowerCase() !== name.toLowerCase() ? current : null,
  }
}

export function loadIndex(dir: string): MirrorIndex {
  try {
    const raw = localStorage.getItem(INDEX_KEY)
    if (!raw) return {}
    const stored = JSON.parse(raw) as { dir?: string; files?: MirrorIndex }
    return stored.dir === dir && stored.files ? stored.files : {}
  } catch {
    return {}
  }
}

export function saveIndex(dir: string, index: MirrorIndex): void {
  try {
    localStorage.setItem(INDEX_KEY, JSON.stringify({ dir, files: index }))
  } catch {
    /* storage unavailable: worst case a later rename leaves the old file behind */
  }
}

/** Notice written into the mirror folder so nobody edits the copies by mistake. */
export const MIRROR_README = 'README - Jnana mirror.txt'
const README_TEXT =
  'Generated by Jnana. Each .md file here is rewritten whenever its note is saved in Jnana ' +
  'and removed when the note is deleted or renamed. Edits made here are overwritten; edit in Jnana instead.\n'

// One queue for every mirror write, so two quick saves of the same note
// (e.g. a rename) can't interleave their write and remove.
let queue: Promise<unknown> = Promise.resolve()
function enqueue(job: () => Promise<void>): Promise<void> {
  const run = queue.then(job)
  queue = run.catch(() => {})
  return run
}

// Autosave fires every ~800 ms; a missing folder must not toast on each one.
let warned = false
function warnOnce(err: unknown): void {
  log.error('[mirror] write failed', err)
  if (warned) return
  warned = true
  toast.error('Markdown mirror: could not update the mirror folder. Check that it still exists.')
}

async function applyPlan(dir: string, plan: MirrorPlan, note: Note | null): Promise<void> {
  if (plan.write && note) {
    const { content, assets } = exportNoteContent(note)
    await invoke<number>('export_notes', { dir, files: [{ name: plan.write, content }], assets })
  }
  if (plan.remove) await invoke<number>('remove_export_files', { dir, names: [plan.remove] })
  saveIndex(dir, plan.index)
  warned = false
}

/** Write (or rename) one note's file. Never rejects: failures are logged and toasted once. */
export function mirrorNote(dir: string, note: Note): Promise<void> {
  return enqueue(() => applyPlan(dir, planSave(loadIndex(dir), note), note)).catch(warnOnce)
}

/** Remove one note's file. Never rejects. */
export function unmirrorNote(dir: string, id: string): Promise<void> {
  return enqueue(() => applyPlan(dir, planDelete(loadIndex(dir), id), null)).catch(warnOnce)
}

/**
 * Write every note in one IPC call (when mirroring is turned on). Rejects on
 * failure so the caller can report it.
 */
export function mirrorAll(dir: string, notes: Note[]): Promise<void> {
  return enqueue(async () => {
    let index = loadIndex(dir)
    const files = [{ name: MIRROR_README, content: README_TEXT }]
    const assets = new Set<string>()
    const removed: string[] = []
    // Notes deleted without a per-note event (Empty Trash, vault delete) drop out
    // here, before the loop, so their names are free for the notes below.
    const live = new Set(notes.map((n) => n.id))
    for (const id of Object.keys(index)) {
      if (live.has(id)) continue
      const plan = planDelete(index, id)
      index = plan.index
      if (plan.remove) removed.push(plan.remove)
    }
    for (const n of notes) {
      const plan = planSave(index, n)
      index = plan.index
      if (plan.remove) removed.push(plan.remove)
      if (!plan.write) continue
      const out = exportNoteContent(n)
      files.push({ name: plan.write, content: out.content })
      out.assets.forEach((a) => assets.add(a))
    }
    await invoke<number>('export_notes', { dir, files, assets: [...assets] })
    // A later note in this batch may have taken a name an earlier one moved off.
    const written = new Set(files.map((f) => f.name.toLowerCase()))
    const names = removed.filter((r) => !written.has(r.toLowerCase()))
    if (names.length) await invoke<number>('remove_export_files', { dir, names })
    saveIndex(dir, index)
    warned = false
  })
}

export async function pickMirrorFolder(): Promise<string | null> {
  const dir = await open({ directory: true, multiple: false, title: 'Choose a folder to mirror your notes into' })
  return typeof dir === 'string' ? dir : null
}
