// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2026 Jnana Project

// Live one-way Markdown mirror. SQLite stays the source of truth; every save
// rewrites that note's .md in a folder the user picked, laid out as
// `<Vault>/<Folder>/<Subfolder>/<Note>.md`, so notes stay readable, greppable
// and git-able without Jnana. The folder is never read back: edits made there
// are overwritten on the next save.

import { invoke } from '@tauri-apps/api/core'
import { open } from '@tauri-apps/plugin-dialog'
import { DEFAULT_VAULT_ID, type Folder, type Note, type Vault } from '../types'
import { getNoteType } from '../lib/noteTypes'
import { toast } from '../lib/toast'
import { log } from '../lib/logger'
import { exportNoteContent, safeName } from './export'
import { listVaults } from './vaults'
import { listFolders } from './folders'
import { getAllNotes } from './notes'

/** note id → `/`-separated path written for it, relative to the mirror folder. */
export type MirrorIndex = Record<string, string>

export interface MirrorPlan {
  index: MirrorIndex
  /** Path to (re)write for this note, or null. */
  write: string | null
  /** Path of this note to delete (its previous location), or null. */
  remove: string | null
}

/** Vault names and the folder tree, for turning a note into a path. */
export interface MirrorTree {
  vaults: Map<string, string>
  folders: Map<string, { name: string; parentId: string | null }>
}

const INDEX_KEY = 'jnana.mirror.index.v1'
/** Guards a parent cycle in bad data; real trees are far shallower. */
const MAX_DEPTH = 32

export function buildTree(vaults: Vault[], folders: Folder[]): MirrorTree {
  return {
    vaults: new Map(vaults.map((v) => [v.id, v.name])),
    folders: new Map(folders.map((f) => [f.id, { name: f.name, parentId: f.parentId }])),
  }
}

/** `[vault, folder, subfolder, …]` directory segments for a note. */
function noteDirs(note: Note, tree: MirrorTree): string[] {
  const chain: string[] = []
  let id = note.folderId ?? null
  for (let depth = 0; id && depth < MAX_DEPTH; depth++) {
    const f = tree.folders.get(id)
    // A folder deleted just before this event: the note is unfiled now.
    if (!f) {
      chain.length = 0
      break
    }
    chain.unshift(safeName(f.name))
    id = f.parentId
  }
  const vault = tree.vaults.get(note.vaultId ?? DEFAULT_VAULT_ID) ?? 'Vault'
  return [safeName(vault), ...chain]
}

/** `assets` reached from a file at `path` (one `../` per directory level). */
function assetDirFor(path: string): string {
  return '../'.repeat(path.split('/').length - 1) + 'assets'
}

/** Plain notes, and typed notes whose type projects to markdown. A canvas's raw JSON isn't a readable .md. */
export function isMirrorable(note: Note): boolean {
  if (!note.kind) return true
  return !!getNoteType(note)?.toExportMarkdown
}

export function planDelete(index: MirrorIndex, id: string): MirrorPlan {
  const current = index[id]
  if (!current) return { index, write: null, remove: null }
  const next = { ...index }
  delete next[id]
  return { index: next, write: null, remove: current }
}

export function planSave(index: MirrorIndex, note: Note, tree: MirrorTree): MirrorPlan {
  if (!isMirrorable(note)) return planDelete(index, note.id)
  const dir = noteDirs(note, tree).join('/')
  const base = safeName(note.title)
  // Case-insensitive: Windows and macOS file systems treat "Same.md" and "same.md" as one file.
  const plain = `${dir}/${base}.md`.toLowerCase()
  const taken = Object.entries(index).some(([id, path]) => id !== note.id && path.toLowerCase() === plain)
  const path = taken ? `${dir}/${base} (${note.id.slice(0, 8)}).md` : `${dir}/${base}.md`
  const current = index[note.id]
  return {
    index: { ...index, [note.id]: path },
    write: path,
    // A case-only rename writes over the same file on disk; removing the "old" path would delete it.
    remove: current && current.toLowerCase() !== path.toLowerCase() ? current : null,
  }
}

export function loadIndex(dir: string): MirrorIndex {
  try {
    const raw = localStorage.getItem(INDEX_KEY)
    if (!raw) return {}
    const stored = JSON.parse(raw) as { dir?: string; files?: MirrorIndex }
    return stored.dir === dir && stored.files ? stored.files : {}
  } catch {
    return {}
  }
}

export function saveIndex(dir: string, index: MirrorIndex): void {
  try {
    localStorage.setItem(INDEX_KEY, JSON.stringify({ dir, files: index }))
  } catch {
    /* storage unavailable: worst case a later rename leaves the old file behind */
  }
}

/** Notice written into the mirror folder so nobody edits the copies by mistake. */
export const MIRROR_README = 'README - Jnana mirror.txt'
const README_TEXT =
  'Generated by Jnana. Each .md file here is rewritten whenever its note is saved in Jnana ' +
  'and removed when the note is deleted, renamed or moved. Edits made here are overwritten; edit in Jnana instead.\n'

// Saves reuse the last tree; mirrorAll (first mirror, and every vault/folder
// change) reloads it. A note saved into a brand-new folder before that reload
// lands at its vault root and is moved by the re-mirror that follows.
let treeCache: Promise<MirrorTree> | null = null
function loadTree(fresh: boolean): Promise<MirrorTree> {
  if (fresh || !treeCache) {
    const load = Promise.all([listVaults(), listFolders()]).then(([v, f]) => buildTree(v, f))
    // A failed load must not stick (or clear a newer one).
    load.catch(() => {
      if (treeCache === load) treeCache = null
    })
    treeCache = load
  }
  return treeCache
}

// One queue for every mirror write, so two quick saves of the same note
// (e.g. a rename) can't interleave their write and remove.
let queue: Promise<unknown> = Promise.resolve()
function enqueue(job: () => Promise<void>): Promise<void> {
  const run = queue.then(job)
  queue = run.catch(() => {})
  return run
}

// Autosave fires every ~800 ms; a missing folder must not toast on each one.
let warned = false
function warnOnce(err: unknown): void {
  log.error('[mirror] write failed', err)
  if (warned) return
  warned = true
  toast.error('Markdown mirror: could not update the mirror folder. Check that it still exists.')
}

async function applyPlan(dir: string, plan: MirrorPlan, note: Note | null): Promise<void> {
  if (plan.write && note) {
    const { content, assets } = exportNoteContent(note, assetDirFor(plan.write))
    await invoke<number>('export_notes', { dir, files: [{ name: plan.write, content }], assets })
  }
  if (plan.remove) await invoke<number>('remove_export_files', { dir, names: [plan.remove] })
  saveIndex(dir, plan.index)
  warned = false
}

/** Write (or rename/move) one note's file. Never rejects: failures are logged and toasted once. */
export function mirrorNote(dir: string, note: Note): Promise<void> {
  return enqueue(async () => applyPlan(dir, planSave(loadIndex(dir), note, await loadTree(false)), note)).catch(warnOnce)
}

/** Remove one note's file. Never rejects. */
export function unmirrorNote(dir: string, id: string): Promise<void> {
  return enqueue(() => applyPlan(dir, planDelete(loadIndex(dir), id), null)).catch(warnOnce)
}

/**
 * Bring the whole folder in line with `notes` in one IPC call: new and moved
 * notes are written, old paths and deleted notes removed. `rewrite` (the
 * default, used when mirroring is turned on) also rewrites notes whose path
 * didn't change. Rejects on failure so the caller can report it.
 */
export function mirrorAll(dir: string, notes: Note[], { rewrite = true } = {}): Promise<void> {
  return enqueue(async () => {
    const tree = await loadTree(true)
    const before = loadIndex(dir)
    let index = before
    const files = [{ name: MIRROR_README, content: README_TEXT }]
    const assets = new Set<string>()
    const removed: string[] = []
    // Notes deleted without a per-note event (Empty Trash, vault delete) drop out
    // here, before the loop, so their names are free for the notes below.
    const live = new Set(notes.map((n) => n.id))
    for (const id of Object.keys(index)) {
      if (live.has(id)) continue
      const plan = planDelete(index, id)
      index = plan.index
      if (plan.remove) removed.push(plan.remove)
    }
    for (const n of notes) {
      const plan = planSave(index, n, tree)
      index = plan.index
      if (plan.remove) removed.push(plan.remove)
      if (!plan.write || (!rewrite && plan.write === before[n.id])) continue
      const out = exportNoteContent(n, assetDirFor(plan.write))
      files.push({ name: plan.write, content: out.content })
      out.assets.forEach((a) => assets.add(a))
    }
    await invoke<number>('export_notes', { dir, files, assets: [...assets] })
    // A later note in this batch may have taken a path an earlier one moved off.
    const written = new Set(files.map((f) => f.name.toLowerCase()))
    const names = removed.filter((r) => !written.has(r.toLowerCase()))
    if (names.length) await invoke<number>('remove_export_files', { dir, names })
    saveIndex(dir, index)
    warned = false
  })
}

/**
 * After a vault/folder rename, move or delete, or a note moving between them:
 * move the affected files. Only changed paths are written. Never rejects.
 */
export async function remirror(dir: string): Promise<void> {
  // ponytail: plans every note per structure change; fine at thousands of notes,
  // track affected folders if this ever shows up in a profile.
  try {
    await mirrorAll(dir, await getAllNotes(), { rewrite: false })
  } catch (err) {
    warnOnce(err)
  }
}

export async function pickMirrorFolder(): Promise<string | null> {
  const dir = await open({ directory: true, multiple: false, title: 'Choose a folder to mirror your notes into' })
  return typeof dir === 'string' ? dir : null
}
